#! /bin/sh
# /etc/init.d/forward-nat
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting nat forwarding"
    
    echo 1 > /proc/sys/net/ipv4/ip_forward
    
    #sudo iptables -A FORWARD -o eth0 -i eth1 -s 192.168.0.0/24 -m conntrack --ctstate NEW -j ACCEPT
    sudo iptables -A FORWARD -o usb0 -s 10.0.0.0/24 -m conntrack --ctstate NEW -j ACCEPT
    sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -t nat -F POSTROUTING
    sudo iptables -t nat -A POSTROUTING -o usb0 -j MASQUERADE
    
    ;;
  stop)
    echo "Stopping nat forwarding"
    echo 0 > /proc/sys/net/ipv4/ip_forward
    ;;
  *)
    echo "Usage: /etc/init.d/forward-nat {start|stop}"
    exit 1
    ;;
esac

exit 0
